/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ContactForm: typeof import('./src/components/ContactForm.vue')['default']
    Cookies: typeof import('./src/components/Cookies.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
  }
}
